import './globals.css'
import type { Metadata } from 'next'
import Nabvar from '@/components/Nabvar'
import Footer from '@/components/Footer'


export const metadata: Metadata = {
  title: 'Consultora',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="bg-white/20 flex-col items-center justify-center">
      <Nabvar/>
      <div className='w-screen flex justify-center'>
      <div className='mt-[27%] sm:mt-[12%] lg:mt-[8%] w-[90vw] flex-col items-center justify-center'>
      <div className=' flex flex-col items-center border-[2px] bg-gray-100 min-h-[100vh] shadow-lg'>
      
        {children}
        </div>
        </div>
        </div>
        <Footer/>
        </body>
    </html>
  )
}
